version: '3'

services:
  game_serv_v2:
    restart: always
    network_mode: host
    build:
      context: ./game_serv_v2
      dockerfile: Dockerfile
    container_name: game_service_v2
     
  # web_service:
  #   restart: always
  #   network_mode: host
  #   build:
  #     context: ./web_server
  #     dockerfile: Dockerfile
  #   container_name: web_service
  
 