

services:
  game_server_two:
    restart: always
    network_mode: host
    build:
      context: ./game_server
      dockerfile: Dockerfile
    container_name: game_service_two
     
  web_server_two:
    restart: always
    network_mode: host
    build:
      context: ./web_serve
      dockerfile: Dockerfile
    container_name: web_service_two
  
 