version: '3'

services:
  game_serv_v2:
    restart: always
    network_mode: host
    build:
      context: ./game_server
      dockerfile: Dockerfile
    container_name: game_service_v2
     
  web_serv_v2:
    restart: always
    network_mode: host
    build:
      context: ./web_serve
      dockerfile: Dockerfile
    container_name: web_service_v2

  deposits:
    restart: always
    network_mode: host
    build:
      context: ./deposits
      dockerfile: Dockerfile
    container_name: deposit
  
 